### ISSUE TITLE
"hyper" command produces: SyntaxError: Unexpected token = in JSON at position 1

### ISSUE THREAD

**Issue by weshicks** [vercel/hyper#3145]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS High Sierra v10.13.5
- **Hyper.app version**: v2.0.0 (Stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/weshicks/4ff3571d3c3d2d6f685b8ce0b742e0b6
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla
## Issue

Hi! This morning I installed a fresh copy of hyper and tried to install the [hyperocean](https://github.com/klauscfhq/hyperocean) theme, and was given the following error: 
```
~ : hyper install hyperocean
undefined:1
{=true
 ^

SyntaxError: Unexpected token = in JSON at position 1
    at JSON.parse (<anonymous>)
    at exports.parse (/Applications/Hyper.app/Contents/Resources/bin/cli.js:19275:17)
    at addConfigFile (/Applications/Hyper.app/Contents/Resources/bin/cli.js:19230:20)
    at Array.forEach (<anonymous>)
    at module.exports (/Applications/Hyper.app/Contents/Resources/bin/cli.js:19243:36)
    at module.exports (/Applications/Hyper.app/Contents/Resources/bin/cli.js:19191:35)
    at Object.<anonymous> (/Applications/Hyper.app/Contents/Resources/bin/cli.js:19102:45)
    at __webpack_require__ (/Applications/Hyper.app/Contents/Resources/bin/cli.js:20:30)
    at Object.<anonymous> (/Applications/Hyper.app/Contents/Resources/bin/cli.js:9914:13)
    at __webpack_require__ (/Applications/Hyper.app/Contents/Resources/bin/cli.js:20:30)
```

![screen shot 2018-08-01 at 8 41 33 am](https://user-images.githubusercontent.com/3211567/43522371-23b74f9e-9567-11e8-8e28-4c8bba49e553.png)

It seems that there's some issue with the bundled `hyper` command on my system, because no matter what I run with it, I get the same error: 

```
~ : hyper --help
undefined:1
{=true
 ^

SyntaxError: Unexpected token = in JSON at position 1
    at JSON.parse (<anonymous>)
    at exports.parse (/Applications/Hyper.app/Contents/Resources/bin/cli.js:19275:17)
    at addConfigFile (/Applications/Hyper.app/Contents/Resources/bin/cli.js:19230:20)
    at Array.forEach (<anonymous>)
    at module.exports (/Applications/Hyper.app/Contents/Resources/bin/cli.js:19243:36)
    at module.exports (/Applications/Hyper.app/Contents/Resources/bin/cli.js:19191:35)
    at Object.<anonymous> (/Applications/Hyper.app/Contents/Resources/bin/cli.js:19102:45)
    at __webpack_require__ (/Applications/Hyper.app/Contents/Resources/bin/cli.js:20:30)
    at Object.<anonymous> (/Applications/Hyper.app/Contents/Resources/bin/cli.js:9914:13)
    at __webpack_require__ (/Applications/Hyper.app/Contents/Resources/bin/cli.js:20:30)
```

![screen shot 2018-08-01 at 8 48 27 am](https://user-images.githubusercontent.com/3211567/43522553-ba5c5b42-9567-11e8-8680-c4a78abbe0ea.png)

I searched for this issue in the issues backlog, and found a [_similar_ issue](https://github.com/zeit/hyper/issues/2829) with the `hyper` command, but not exactly the same thing. Any ideas? (Apologies if this has already been documented as an issue, I searched but wasn't able to find the exact problem I'm having.)

**Comment by RichiRets** [comment]
Any updates?

**Comment by RichiRets** [comment]
I have this issue too

**Comment by LabhanshAgrawal** [comment]
Closing as this is for v2, please open a new issue if you face this in v3
