### ISSUE TITLE
Minor bug : Hyper crashes when .hyper.js is a broken link

### ISSUE THREAD

**Issue by erik-helmers** [vercel/hyper#3743]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 18.04 (irrelevant, I think ?)
- **Hyper.app version**: 3.0.2

## Issue

Hello there !

There's a little edge case bug that happens when loading .hyper.js config file.
My ~/.hyper.js file is a link pointing to a file in another place ; and when this link was broken Hyper wouldn't launch at all, giving this error message: 

```
{ Error: ENOENT: no such file or directory, open '/home/erik-helmers/.hyper.js'
    at Object.fs.openSync (fs.js:577:3)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at fs.writeFileSync (fs.js:1321:33)
    at _write (/opt/Hyper/resources/app.asar/config/import.js:17:3)
    at _importConf (/opt/Hyper/resources/app.asar/config/import.js:114:7)
    at exports._import (/opt/Hyper/resources/app.asar/config/import.js:124:20)
    at Object.exports.setup (/opt/Hyper/resources/app.asar/config.js:98:9)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/index.js:61:8)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/index.js:275:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/erik-helmers/.hyper.js' }

A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'defaultCfg' of undefined
    at exports._import (/opt/Hyper/resources/app.asar/config/import.js:125:28)
    at Object.exports.setup (/opt/Hyper/resources/app.asar/config.js:98:9)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/index.js:61:8)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/index.js:275:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Object.<anonymous> (/opt/Hyper/resources/electron.asar/browser/init.js:189:8)
```

Anyway this isn't a very serious problem, but here you go.
Thanks for the great app !

**Comment by jcklpe** [comment]
I'm having a thing where my link is pointing to the correct place and it's still breaking. Specifically on Windows.
