### ISSUE TITLE
Unexpected Token

### ISSUE THREAD

**Issue by RichiRets** [vercel/hyper#4066]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Windows 10**: 
- **Latest I just installed it**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

![Screenshot_1](https://user-images.githubusercontent.com/57653696/70872219-70469d00-1fe1-11ea-923e-43ee35fd237a.png)

Hello I have encountered this issue and haven't found any similar situations. Please help thanks! Themes are not working when I added verminal manually in hyper.js

**Comment by mosesontheweb** [comment]
Hi,
same here on Ubuntu 18.04:
```
/opt/Hyper/resources/bin/cli.js:26017
                throw this.unexpectedTokenError(token, message);
                ^
Error: Line 15: Unexpected token ,
    at ErrorHandler.constructError (/opt/Hyper/resources/bin/cli.js:29026:22)
    at ErrorHandler.createError (/opt/Hyper/resources/bin/cli.js:29042:27)
    at JSXParser.Parser.unexpectedTokenError (/opt/Hyper/resources/bin/cli.js:26007:39)
    at JSXParser.Parser.throwUnexpectedToken (/opt/Hyper/resources/bin/cli.js:26017:21)
    at JSXParser.Parser.parseObjectProperty (/opt/Hyper/resources/bin/cli.js:26606:23)
    at JSXParser.Parser.parseObjectInitializer (/opt/Hyper/resources/bin/cli.js:26617:35)
    at JSXParser.Parser.inheritCoverGrammar (/opt/Hyper/resources/bin/cli.js:26300:37)
    at JSXParser.Parser.parsePrimaryExpression (/opt/Hyper/resources/bin/cli.js:26369:38)
    at JSXParser.parsePrimaryExpression (/opt/Hyper/resources/bin/cli.js:24488:97)
    at JSXParser.Parser.inheritCoverGrammar (/opt/Hyper/resources/bin/cli.js:26300:37)
```
Any hints?
Regards, Thomas

**Comment by MoonPadUSer** [comment]
I have the same issue on macOS 10.14

**Comment by raeokay** [comment]
Same issue on Windows 10 18363.1256

**Comment by LabhanshAgrawal** [comment]
might've made a mistake while editing the config file, please post it here
