### ISSUE TITLE
AUR installing error

### ISSUE THREAD

**Issue by tz4678** [vercel/hyper#4255]
- **OS version and name**: 

```zsh
$ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux

$ uname -r
5.5.2-arch1-1
```

- **Hyper.app version**: 3.0.2-1

I have installed [asdf-vm](https://github.com/asdf-vm/asdf) version manager. Maybe this is the cause of the error?

```zsh
$ which python 
/home/sergey/.asdf/shims/python

$ which python2
/home/sergey/.asdf/shims/python2

$ which node   
/home/sergey/.asdf/shims/node

$ ls /usr/bin/pyt*
/usr/bin/python   /usr/bin/python2.7         /usr/bin/python2-config  /usr/bin/python3.8         /usr/bin/python3-config
/usr/bin/python2  /usr/bin/python2.7-config  /usr/bin/python3         /usr/bin/python3.8-config  /usr/bin/python-config
```

```zsh
$ yay -S hyper
...
$ electron-rebuild -f -w app/node_modules/node-pty -m app
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.15.0 | linux | x64
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /home/sergey/.asdf/shims/python2 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack unknown command: python2. Perhaps you have to reshim?
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:295:12)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:430:11)
gyp ERR! stack     at Socket.emit (events.js:223:5)
gyp ERR! stack     at Pipe.<anonymous> (net.js:664:12)
gyp ERR! System Linux 5.5.2-arch1-1
gyp ERR! command "/home/sergey/.asdf/installs/nodejs/12.15.0/bin/node" "/home/sergey/.cache/yay/hyper/src/hyper-3.0.2/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=3.1.3" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd /home/sergey/.cache/yay/hyper/src/hyper-3.0.2/app/node_modules/node-pty
gyp ERR! node -v v12.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.15.0 | linux | x64
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /home/sergey/.asdf/shims/python2 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack unknown command: python2. Perhaps you have to reshim?
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:295:12)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:430:11)
gyp ERR! stack     at Socket.emit (events.js:223:5)
gyp ERR! stack     at Pipe.<anonymous> (net.js:664:12)
gyp ERR! System Linux 5.5.2-arch1-1
gyp ERR! command "/home/sergey/.asdf/installs/nodejs/12.15.0/bin/node" "/home/sergey/.cache/yay/hyper/src/hyper-3.0.2/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=3.1.3" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd /home/sergey/.cache/yay/hyper/src/hyper-3.0.2/app/node_modules/node-pty
gyp ERR! node -v v12.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (/home/sergey/.cache/yay/hyper/src/hyper-3.0.2/node_modules/spawn-rx/lib/src/index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (/home/sergey/.cache/yay/hyper/src/hyper-3.0.2/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:242:16)
    at SafeSubscriber.error (/home/sergey/.cache/yay/hyper/src/hyper-3.0.2/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:201:26)
    at Subscriber._error (/home/sergey/.cache/yay/hyper/src/hyper-3.0.2/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:132:26)
    at Subscriber.error (/home/sergey/.cache/yay/hyper/src/hyper-3.0.2/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:106:18)
    at MapSubscriber.Subscriber._error (/home/sergey/.cache/yay/hyper/src/hyper-3.0.2/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:132:26)
    at MapSubscriber.Subscriber.error (/home/sergey/.cache/yay/hyper/src/hyper-3.0.2/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:106:18)
    at SafeSubscriber._next (/home/sergey/.cache/yay/hyper/src/hyper-3.0.2/node_modules/spawn-rx/lib/src/index.js:251:65)
    at SafeSubscriber.__tryOrSetError (/home/sergey/.cache/yay/hyper/src/hyper-3.0.2/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:251:16)
    at SafeSubscriber.next (/home/sergey/.cache/yay/hyper/src/hyper-3.0.2/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:191:27)
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
==> ERROR: A failure occurred in prepare().
    Aborting...
Error making: hyper
```

**Comment by bet4it** [comment]
Use `yay -S hyper-git`

**Comment by tz4678** [comment]
> yay -S hyper-git

thnx

**Comment by LabhanshAgrawal** [comment]
@tz4678 can you close this issue now, as it's solved.
