### ISSUE TITLE
Can't run hyper cli in windows 10 wsl

### ISSUE THREAD

**Issue by supasonk** [vercel/hyper#4611]
- [ x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 WSL2
- **Hyper.app version**:  3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/supasonk/534fc05017692ffeba4f7bfb56139e4c
- **Relevant information from devtools** Plugin hyper-material-theme (3.0.1) loaded.
Disabling Chromium GPU blacklist
running in prod mode
electron will open file://C:\Users\user\AppData\Local\hyper\app-3.0.2\resources\app.asar\index.html
Error while loading devtools extensions Error: Cannot create process, error code: 267
    at new WindowsPtyAgent (C:\Users\user\AppData\Local\hyper\app-3.0.2\resources\app.asar\node_modules\node-pty\lib\windowsPtyAgent.js:75:43)
    at new WindowsTerminal (C:\Users\user\AppData\Local\hyper\app-3.0.2\resources\app.asar\node_modules\node-pty\lib\windowsTerminal.js:46:24)
    at spawn (C:\Users\user\AppData\Local\hyper\app-3.0.2\resources\app.asar\node_modules\node-pty\lib\index.js:29:12)
    at Session.init (C:\Users\user\AppData\Local\hyper\app-3.0.2\resources\app.asar\session.js:111:18)
    at new Session (C:\Users\user\AppData\Local\hyper\app-3.0.2\resources\app.asar\session.js:83:10)
    at createSession (C:\Users\user\AppData\Local\hyper\app-3.0.2\resources\app.asar\ui\window.js:116:23)
    at createInitialSession (C:\Users\user\AppData\Local\hyper\app-3.0.2\resources\app.asar\ui\window.js:124:32)
    at new Window (C:\Users\user\AppData\Local\hyper\app-3.0.2\resources\app.asar\ui\window.js:140:26)
    at createWindow (C:\Users\user\AppData\Local\hyper\app-3.0.2\resources\app.asar\index.js:157:22)
    at installDevExtensions.then (C:\Users\user\AppData\Local\hyper\app-3.0.2\resources\app.asar\index.js:177:7)
- **The issue is reproducible in vanilla Hyper.app**: Is Vanila

## Issue
I can't run the hyper cli when i run the command the above error occured. my machine are windows 10 with wsl2 running in ubuntu.

**Comment by fyrfli** [comment]
Encountering the same error.

**Comment by LabhanshAgrawal** [comment]
can you try with the [ci build](https://github.com/vercel/hyper/actions/runs/157826845) once

**Comment by garyyeap** [comment]
> 
> 
> can you try with the [ci build](https://github.com/vercel/hyper/actions/runs/157826845) once

Flashing back as soon as it opens

**Comment by AkimaLunar** [comment]
Looks like this issue is still open. Just wondering if there have been any thoughts on how to fix this. I have the same issue with the same OS and Hyper.app version.

**Comment by franciscocandido** [comment]
One of the ways to solve this problem and pasting it: `alias hyper="cmd.exe /c hyper"` in `zshrc` or `bashrc` file

It worked for me on Windows 10 with WSL2 😊

**Comment by dominikfiala** [comment]
I just tried to install a hypercwd plugin and encountered the same issue. `alias hyper="cmd.exe /c hyper"` in `bashrc` helped with the installation, but I'm running into JS error when opening a new tab now in WSL. It works perfectly in Windows PowerShell though.
JS error enclosed.
![Annotation 2020-09-12 130914](https://user-images.githubusercontent.com/3163672/92994299-75e1fc80-f4f9-11ea-9c71-6e12f9fef033.jpg)

**Comment by franciscocandido** [comment]
> I just tried to install a hypercwd plugin and encountered the same issue. `alias hyper="cmd.exe /c hyper"` in `bashrc` helped with the installation, but I'm running into JS error when opening a new tab now in WSL. It works perfectly in Windows PowerShell though.
> JS error enclosed.
> ![Annotation 2020-09-12 130914](https://user-images.githubusercontent.com/3163672/92994299-75e1fc80-f4f9-11ea-9c71-6e12f9fef033.jpg)

I have the same error just removing the line after installing the plugins

**Comment by petahbred** [comment]
@dominikfiala Have you had any fixing hypercwd?

**Comment by jcrben** [comment]
3.1.0-canary.4 worked better for me

**Comment by rafaelje** [comment]
if you need to install something urgent change the .hyper.js file with:
```    
shell: '',
shellArgs: [],
```
restart the terminal

now you should have the default cmd.exe and you can run

```
hyper install....
```

**Comment by altosaar** [comment]
Having the same issue!

**Comment by ajgaokar5** [comment]
![267](https://github.com/vercel/hyper/assets/15631212/48b13ecb-f4ab-4fdd-96f9-fb80d03c9eb8)

**Comment by h2kyaw** [comment]
`hyper u hypercwd`

I uninstalled hypercwd and problem fixed.

**Comment by zaadevofc** [comment]
> `hyper u hypercwd`
> 
> I uninstalled hypercwd and problem fixed.

it't work for mee, nice one bruhh. Thanks
