### ISSUE TITLE
Correct behaviour , Launch Hyper

### ISSUE THREAD

**Issue by vaclavbenes** [vercel/hyper#4719]
I d like to debug hyper js in debug menu, but debug exit with code 0 and no hyper instance was created.
I am confused. is it correct behaviour?

1. `yarn run dev`

```sh
─$ yarn run dev                                                                                           
...
[Webpack]         + 185 hidden modules
[Webpack]     
[Webpack]     WARNING in ./node_modules/args/lib/version.js 18:11-24
[Webpack]     Critical dependency: the request of a dependency is an expression
[Webpack]      @ ./node_modules/args/lib/index.js
[Webpack]      @ ./cli/index.ts
[Webpack]     
[Webpack]     WARNING in ./node_modules/keyv/src/index.js 18:14-40
[Webpack]     Critical dependency: the request of a dependency is an expression
[Webpack]      @ ./node_modules/cacheable-request/src/index.js
[Webpack]      @ ./node_modules/got/dist/source/core/index.js
[Webpack]      @ ./node_modules/got/dist/source/create.js
[Webpack]      @ ./node_modules/got/dist/source/index.js
[Webpack]      @ ./cli/index.ts
```

2. `Launch hyper` < vscode debug menu

```sh
Debugger listening on ws://127.0.0.1:53874/3ddca509-b9f0-4266-95b7-a337fab14986
For help, see: https://nodejs.org/en/docs/inspector
Error: dest already exists.
    at doRename (/Users/vaclav.benes/Git/hyper/target/node_modules/fs-extra/lib/move-sync/move-sync.js:25:34)
    at Object.moveSync (/Users/vaclav.benes/Git/hyper/target/node_modules/fs-extra/lib/move-sync/move-sync.js:17:10)
    at saveAsBackup (/Users/vaclav.benes/Git/hyper/target/config/import.js:30:24)
    at migrateHyper2Config (/Users/vaclav.benes/Git/hyper/target/config/import.js:68:32)
    at _importConf (/Users/vaclav.benes/Git/hyper/target/config/import.js:83:9)
    at Object.exports._import (/Users/vaclav.benes/Git/hyper/target/config/import.js:118:22)
    at Object.exports.setup (/Users/vaclav.benes/Git/hyper/target/config.js:113:20)
    at Object.<anonymous> (/Users/vaclav.benes/Git/hyper/target/index.js:74:8)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
(node:22214) ExtensionLoadWarning: Warnings loading extension at /Users/vaclav.benes/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi: Unrecognized manifest key 'browser_action'. Unrecognized manifest key 'minimum_chrome_version'. Unrecognized manifest key 'update_url'. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system. 
(node:22214) ExtensionLoadWarning: Warnings loading extension at /Users/vaclav.benes/Library/Application Support/Electron/extensions/lmhkpmbekcpmknklioeibfkpmmfibljd: Unrecognized manifest key 'commands'. Unrecognized manifest key 'homepage_url'. Unrecognized manifest key 'page_action'. Unrecognized manifest key 'short_name'. Unrecognized manifest key 'update_url'. Permission 'notifications' is unknown or URL pattern is malformed. Permission 'contextMenus' is unknown or URL pattern is malformed. Permission 'tabs' is unknown or URL pattern is malformed. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system. 
Notification messages fetch error SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at /Users/vaclav.benes/Git/hyper/target/node_modules/electron-fetch/lib/index.js:240:55
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
Debugger listening on ws://127.0.0.1:53874/3ddca509-b9f0-4266-95b7-a337fab14986
For help, see: https://nodejs.org/en/docs/inspector
Waiting for the debugger to disconnect...
Process exited with code 0

```

- **OS version and name**: macOs Catalina 10.15.5
- **Hyper.app version**: 3.1.0-canary.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js** https://gist.github.com/vaclavbenes/987400af799f56b55875ed23130a5827

**Comment by vaclavbenes** [comment]
![ezgif com-crop](https://user-images.githubusercontent.com/25709267/86900403-96619500-c10b-11ea-9d0e-2f60082b64e9.gif)

**Comment by LabhanshAgrawal** [comment]
Not sure why this happened
I tried the same and it worked as expected
maybe try `git clean -xdf` (deletes all untracked changes and files) and `yarn` to reinstall all the deps

**Comment by vaclavbenes** [comment]
works with stable debuger

<img width="660" alt="Screenshot 2020-07-08 at 13 20 47" src="https://user-images.githubusercontent.com/25709267/86912787-e2b5d080-c11d-11ea-8a8c-f2cdaa1a195a.png">

**Comment by LabhanshAgrawal** [comment]
closing as it's an upstream issue.
Feel free to open a pr if you can adapt the `launch.json` or any other required setup to work with both stable and preview debugger.
