### ISSUE TITLE
Unable to install plugins in Hyper

### ISSUE THREAD

**Issue by cldmello** [vercel/hyper#4786]
- [x] Your Hyper.app version is **3.0.2**. Please verify your using the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

  ---
  - **Any relevant information from devtools?** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:

  - **Is the issue reproducible in vanilla Hyper.app?**

## Issue

I have a Hyper terminal client install that built from AUR in Arch Linux. The client works fine. However, I'm having issues installing hyper plugins. For instance, when I run "hyper i hyper-one-dark" (or that matter, any other plugin), I get the below error message. Any help here will be appreciated! 

Note: I do not have this issue on Linux Mint or Ubuntu since I installed using your .deb package from the website. 

Disabling Chromium GPU blacklist
running in prod mode
electron will open file:///usr/lib/hyper/resources/app.asar/index.html
Checking for notification messages
Notification messages fetch error SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at consumeBody.call.then.buffer (/usr/lib/hyper/resources/app.asar/node_modules/electron-fetch/lib/index.js:240:55)
    at process._tickCallback (internal/process/next_tick.js:68:7)

 - **Hyper version**: undefined "3.0.2"

 - **OS ARCH VERSION:** linux x64 5.4.52-1-MANJARO
 - **Electron:** 3.1.3  **LANG:** en_US.UTF-8
 - **SHELL:** /bin/bash   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "updateChannel": "stable",
  "fontSize": 10,
  "fontFamily": "\"Fira Code\", Hack, Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "fontWeight": "normal",
  "fontWeightBold": "bold",
  "lineHeight": 1,
  "letterSpacing": 0,
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorAccentColor": "#000",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#c7c7c7",
  "backgroundColor": "#0c0c0c",
  "selectionColor": "rgba(248,28,229,0.3)",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#C51E14",
    "green": "#1DC121",
    "yellow": "#C7C329",
    "blue": "#0A2FC4",
    "magenta": "#C839C5",
    "cyan": "#20C5C6",
    "white": "#C7C7C7",
    "lightBlack": "#686868",
    "lightRed": "#FD6F6B",
    "lightGreen": "#67F86F",
    "lightYellow": "#FFFA72",
    "lightBlue": "#6A76FB",
    "lightMagenta": "#FD7CFC",
    "lightCyan": "#68FDFE",
    "lightWhite": "#FFFFFF"
  },
  "shell": "/bin/zsh",
  "shellArgs": [
    "--login"
  ],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false,
  "defaultSSHApp": true,
  "quickEdit": false,
  "macOptionSelectionMode": "vertical",
  "webGLRenderer": false
}

          {
  "plugins": [],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by cldmello** [comment]
Found the solution online. 

Apparently, we need to export the bin path. 

export PATH=/usr/lib/hyper/resources/bin:$PATH

This worked!
