### ISSUE TITLE
Unable to install theme

### ISSUE THREAD

**Issue by Yakumo-Yukari** [vercel/hyper#4802]
➜ hyper i hyper-material-theme
/opt/Hyper/resources/bin/cli.js:19156
      getProperties = memoize(() => getParsedFile().program.body[0].expression.right.properties),
                                                                                    ^

TypeError: Cannot read property 'properties' of undefined
    at memoize (/opt/Hyper/resources/bin/cli.js:19156:85)
    at d (/opt/Hyper/resources/bin/cli.js:19141:22)
    at memoize (/opt/Hyper/resources/bin/cli.js:19157:34)
    at d (/opt/Hyper/resources/bin/cli.js:19141:22)
    at Object.install (/opt/Hyper/resources/bin/cli.js:19187:37)
    at Args.args.command (/opt/Hyper/resources/bin/cli.js:9934:45)
    at Args.runCommand (/opt/Hyper/resources/bin/cli.js:11318:37)
    at Args.module.exports [as parse] (/opt/Hyper/resources/bin/cli.js:15089:10)
    at main (/opt/Hyper/resources/bin/cli.js:9991:18)
    at Object.module.exports.name (/opt/Hyper/resources/bin/cli.js:10038:1)

**Comment by LabhanshAgrawal** [comment]
Fixed in #4706
