### ISSUE TITLE
hyper i hyper-plugin returns unexpectedTokenError

### ISSUE THREAD

**Issue by mcdonaldryn** [vercel/hyper#4895]
/Applications/Hyper.app/Contents/Resources/bin/cli.js:26017
                throw this.unexpectedTokenError(token, message);
                ^
Error: Line 135: Unexpected end of input
    at ErrorHandler.constructError (/Applications/Hyper.app/Contents/Resources/bin/cli.js:29026:22)
    at ErrorHandler.createError (/Applications/Hyper.app/Contents/Resources/bin/cli.js:29042:27)
    at JSXParser.Parser.unexpectedTokenError (/Applications/Hyper.app/Contents/Resources/bin/cli.js:26007:39)
    at JSXParser.Parser.throwUnexpectedToken (/Applications/Hyper.app/Contents/Resources/bin/cli.js:26017:21)
    at JSXParser.Parser.parseObjectPropertyKey (/Applications/Hyper.app/Contents/Resources/bin/cli.js:26518:29)
    at JSXParser.Parser.parseObjectProperty (/Applications/Hyper.app/Contents/Resources/bin/cli.js:26549:25)
    at JSXParser.Parser.parseObjectInitializer (/Applications/Hyper.app/Contents/Resources/bin/cli.js:26617:35)
    at JSXParser.Parser.inheritCoverGrammar (/Applications/Hyper.app/Contents/Resources/bin/cli.js:26300:37)
    at JSXParser.Parser.parsePrimaryExpression (/Applications/Hyper.app/Contents/Resources/bin/cli.js:26369:38)
    at JSXParser.parsePrimaryExpression (/Applications/Hyper.app/Contents/Resources/bin/cli.js:24488:97)

**Comment by LabhanshAgrawal** [comment]
duplicate #4066
