### ISSUE TITLE
Error while loading devtools extensions TypeError: config.css.replace is not a function

### ISSUE THREAD

**Issue by joshunger** [vercel/hyper#4966]
Version 3.0.2.

```
➜  ~ hyper -v
Plugin hyper-dracula (0.1.9) loaded.

Disabling Chromium GPU blacklist

running in prod mode
electron will open file:///Applications/Hyper.app/Contents/Resources/app.asar/index.html

Error while loading devtools extensions TypeError: config.css.replace is not a function
    at Object.keys.forEach.pattern (/Applications/Hyper.app/Contents/Resources/app.asar/config.js:150:43)
    at Array.forEach (<anonymous>)
    at Object.exports.htermConfigTranslate.config [as htermConfigTranslate] (/Applications/Hyper.app/Contents/Resources/app.asar/config.js:147:32)
    at Object.exports.getDecoratedConfig (/Applications/Hyper.app/Contents/Resources/app.asar/plugins.js:419:35)
    at createWindow (/Applications/Hyper.app/Contents/Resources/app.asar/index.js:114:29)
    at installDevExtensions.then (/Applications/Hyper.app/Contents/Resources/app.asar/index.js:177:7)
```

**Comment by joshunger** [comment]
Deleting `~/.hyper.js` fixed the issue 🤔

**Comment by LabhanshAgrawal** [comment]
Might've been some mistake in editing the config, reopen if you face this again
