### ISSUE TITLE
js failure?

### ISSUE THREAD

**Issue by docgonzo2015** [vercel/hyper#5210]
I've installed like in the instruction written and  now i'm got:
$ hyper i hyper-rose-pine

`AppData\Local\hyper\app-3.0.2\resources\bin\cli.js:26017
                throw this.unexpectedTokenError(token, message);
                ^
Error: Line 1: Unexpected identifier
    at ErrorHandler.constructError (C..\AppData\Local\hyper\app-3.0.2\resources\bin\cli.js:29026:22)
    at ErrorHandler.createError (\AppData\Local\hyper\app-3.0.2\resources\bin\cli.js:29042:27)
    at JSXParser.Parser.unexpectedTokenError (AppData\Local\hyper\app-3.0.2\resources\bin\cli.js:26007:39)
    at JSXParser.Parser.throwUnexpectedToken (ppData\Local\hyper\app-3.0.2\resources\bin\cli.js:26017:21)
    at JSXParser.Parser.consumeSemicolon (pData\Local\hyper\app-3.0.2\resources\bin\cli.js:26312:23)
    at JSXParser.Parser.parseLabelledStatement (ppData\Local\hyper\app-3.0.2\resources\bin\cli.js:28039:19)
    at JSXParser.Parser.parseStatement (AppData\Local\hyper\app-3.0.2\resources\bin\cli.js:28132:97)`

any idea?

**Comment by mvllow** [comment]
Unrelated to the error but if you could try adding `hyper-rose-pine` to your plugins array does that install the theme properly?

```js
// ~/.hyper.js
module.exports = {
  plugins: [ "hyper-rose-pine" ]
}
```

**Comment by LabhanshAgrawal** [comment]
@docgonzo2015 can you post your config?
