### ISSUE TITLE
Unexpected token T in JSON at position 0

### ISSUE THREAD

**Issue by doggo-rules** [vercel/hyper#5516]
- [X] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: ArchLabs
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://paste.gg/p/anonymous/f8386a238ced462eaab088014f400069
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
So, I just installed Hyper and I get this error when running it. I use ArchLabs with XFCE4. The full error is here:
```
zenity, kdialog, Xdialog missing. Skipping /tmp/.mount_hyperY9b3XY/AppRun.
Disabling Chromium GPU blacklist
running in prod mode
electron will open file:///tmp/.mount_hyperY9b3XY/resources/app.asar/index.html
Setting Hyper as default client for ssh:// protocol
Checking for notification messages
Notification messages fetch error SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at consumeBody.call.then.buffer (/tmp/.mount_hyperY9b3XY/resources/app.asar/node_modules/electron-fetch/lib/index.js:240:55)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by doggo-rules** [comment]
Whoops, seems like there is already a (closed) issue with the same problem here https://github.com/vercel/hyper/issues/4750
I didn't see it while searching, closing this.
