### ISSUE TITLE
Unable to use `hyper` command

### ISSUE THREAD

**Issue by Gizmotronn** [vercel/hyper#5591]
- **OS version and name**: OSX Big Sur on 2020 M1 Air
- **Hyper.app version**: Current (3.1)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Gizmotronn/6469b65a73425adcd080e8c9464f0272
- 
- Is Vanilla

## Issue
Two main issues:

Using `hyper I ...` command results in the following error:

```bash
hyper i hyper-npm-theme

/Applications/Hyper.app/Contents/Resources/bin/cli.js:26017
                throw this.unexpectedTokenError(token, message);
                ^
Error: Line 181: Unexpected string
    at ErrorHandler.constructError (/Applications/Hyper.app/Contents/Resources/bin/cli.js:29026:22)
    at ErrorHandler.createError (/Applications/Hyper.app/Contents/Resources/bin/cli.js:29042:27)
    at JSXParser.Parser.unexpectedTokenError (/Applications/Hyper.app/Contents/Resources/bin/cli.js:26007:39)
    at JSXParser.Parser.throwUnexpectedToken (/Applications/Hyper.app/Contents/Resources/bin/cli.js:26017:21)
    at JSXParser.Parser.expect (/Applications/Hyper.app/Contents/Resources/bin/cli.js:26183:19)
    at JSXParser.Parser.parseArrayInitializer (/Applications/Hyper.app/Contents/Resources/bin/cli.js:26442:27)
    at JSXParser.Parser.inheritCoverGrammar (/Applications/Hyper.app/Contents/Resources/bin/cli.js:26300:37)
    at JSXParser.Parser.parsePrimaryExpression (/Applications/Hyper.app/Contents/Resources/bin/cli.js:26366:38)
    at JSXParser.parsePrimaryExpression (/Applications/Hyper.app/Contents/Resources/bin/cli.js:24488:97)
    at JSXParser.Parser.inheritCoverGrammar (/Applications/Hyper.app/Contents/Resources/bin/cli.js:26300:37)
```

Also, (OSX Menu Bar > Plugins > Update & Plugins > Install Hyper CLI) appear to be empty buttons - as in, they do not work

This is on a fresh install of Hyper. New themes, plugins are set in `.hyper.js` but do not work.

**Comment by LabhanshAgrawal** [comment]
The config looks like it's a carryover from an earlier version.
Can you rename/delete the config file and reopen hyper. Then set your modifications in the newly generated config.
Also please all this try with the latest build i.e. https://github.com/vercel/hyper/actions/runs/853502590#artifacts
From your config
You don't need the ligatures and search plugins with the new build (you can enable ligature from config)
The plugins are affected a bit by the order they are listed. You may have multiple themes and they can interfere with each other.

**Comment by LabhanshAgrawal** [comment]
Missing commas at the end of lines 22,180,181,182 and 184 in your config
