### ISSUE TITLE
3.1.0 Fails to start in ubuntu 18.04

### ISSUE THREAD

**Issue by luis8** [vercel/hyper#5755]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: ubuntu 18.04
- **Hyper.app version**: 3.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
`./Hyper-3.1.0.AppImage 
Plugin hyper-search (0.4.0) loaded.
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /tmp/.mount_Hyper-gxbGOV/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /tmp/.mount_Hyper-gxbGOV/resources/app.asar/node_modules/node-pty/lib/index.js
- /tmp/.mount_Hyper-gxbGOV/resources/app.asar/session.js
- /tmp/.mount_Hyper-gxbGOV/resources/app.asar/ui/window.js
- /tmp/.mount_Hyper-gxbGOV/resources/app.asar/index.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function._load (/tmp/.mount_Hyper-gxbGOV/resources/app.asar/plugins.js:97:37)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/tmp/.mount_Hyper-gxbGOV/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/.mount_Hyper-gxbGOV/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/tmp/.mount_Hyper-gxbGOV/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/tmp/.mount_Hyper-gxbGOV/resources/app.asar/session.js',
    '/tmp/.mount_Hyper-gxbGOV/resources/app.asar/ui/window.js',
    '/tmp/.mount_Hyper-gxbGOV/resources/app.asar/index.js',
    undefined
  ]
}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: `node-pty` failed to load. Typically this means that it was built incorrectly. Please check the `readme.md` to more info.
    at createNodePtyError (/tmp/.mount_Hyper-gxbGOV/resources/app.asar/session.js:33:34)
    at Object.<anonymous> (/tmp/.mount_Hyper-gxbGOV/resources/app.asar/session.js:40:11)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function._load (/tmp/.mount_Hyper-gxbGOV/resources/app.asar/plugins.js:97:37)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)`

**Comment by luis8** [comment]
I forked the repo and build it using 
`yarn run dist`
and those dist files work correctly.

I guess the one published in the download page is broken.

**Comment by dwisiswant0** [comment]
Yeah, same with me. After upgrading Hyper won't launch.

**Comment by LabhanshAgrawal** [comment]
Does the one from previous release work?
https://github.com/vercel/hyper/releases/tag/v3.1.0-canary.6

**Comment by Sangkwun** [comment]
The same error occurred to me.

**Comment by Sangkwun** [comment]
@LabhanshAgrawal 
https://github.com/vercel/hyper/releases/tag/v3.1.0-canary.6 also does not work.
```
 sangkwun@sangkwun-ThinkPad-X390  ~  hyper -v          ✔  10183  20:21:04 
Plugin hyper-statusline (1.7.6) loaded.

Plugin hyper-dark-scrollbar (1.2.4) loaded.

Plugin hypercwd (1.4.0) loaded.

Plugin hyper-oceanic-next (0.0.2) loaded.

innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Hyper/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /opt/Hyper/resources/app.asar/node_modules/node-pty/lib/index.js
- /opt/Hyper/resources/app.asar/session.js
- /opt/Hyper/resources/app.asar/ui/window.js
- /opt/Hyper/resources/app.asar/index.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function._load (/opt/Hyper/resources/app.asar/plugins.js:97:37)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/opt/Hyper/resources/app.asar/session.js',
    '/opt/Hyper/resources/app.asar/ui/window.js',
    '/opt/Hyper/resources/app.asar/index.js',
    undefined
  ]
}

A JavaScript error occurred in the main process
Uncaught Exception:
Error: `node-pty` failed to load. Typically this means that it was built incorrectly. Please check the `readme.md` to more info.
    at createNodePtyError (/opt/Hyper/resources/app.asar/session.js:33:34)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/session.js:40:11)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function._load (/opt/Hyper/resources/app.asar/plugins.js:97:37)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)

[6110:0717/202105.823351:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
```

**Comment by Sangkwun** [comment]
- 3.1.0-canary.6 (failed)
- 3.1.0-canary.5 (failed)
- 3.1.0-canary.4(Work)

**Comment by Sangkwun** [comment]
I suggest using [3.1.0-canary.4](https://github.com/vercel/hyper/releases/tag/v3.1.0-canary.4) until the issue is solved.

As mentioned in https://github.com/vercel/hyper/issues/2605#issuecomment-368307108
The release notification can be hidden by setting the `notification_indicator` in preference.
```
css: '.notification_indicator{display:none;}',
```

**Comment by dwisiswant0** [comment]
> Does the one from previous release work?
> https://github.com/vercel/hyper/releases/tag/v3.1.0-canary.6

Yes it is.

**Comment by LabhanshAgrawal** [comment]
Can you all try the deb x64 from https://github.com/vercel/hyper/releases/download/v3.1.0/hyper_3.1.0_amd64.deb
Will help in finding out if it's a AppImage specific issue.

**Comment by dwisiswant0** [comment]
> Can you all try the deb x64 from https://github.com/vercel/hyper/releases/download/v3.1.0/hyper_3.1.0_amd64.deb
> Will help in finding out if it's a AppImage specific issue.

I'm using the `deb` version, and the error looks the same.

**Comment by LabhanshAgrawal** [comment]
I see
I also tested with ubuntu 18 and got the error, but it's working in ubuntu 20.
Can you try the file from https://github.com/LabhanshAgrawal/hyper/actions/runs/1041868121#artifacts
It's built on ubuntu 18, if it works for both 18 and 20 then we can use it instead.

**Comment by Sangkwun** [comment]
It works on https://github.com/LabhanshAgrawal/hyper/actions/runs/1041868121#artifacts

**Comment by LabhanshAgrawal** [comment]
@Sangkwun also try the one from https://github.com/LabhanshAgrawal/hyper/actions/runs/1025164478#artifacts
It's built on ubuntu 20 but uses pre-built node-pty

**Comment by Sangkwun** [comment]
https://github.com/LabhanshAgrawal/hyper/actions/runs/1025164478#artifacts doesn't work.

**Comment by LabhanshAgrawal** [comment]
Yeah, later realized that electron-builder also rebuilds the native dependencies.
You can try out https://github.com/LabhanshAgrawal/hyper/actions/runs/1043933646#artifacts , have disabled that rebuild also. It didn't work for me though

@Tyriar can you please help out a bit here. Having issues with node-pty on Ubuntu 18 unless rebuilt on the same.

**Comment by LabhanshAgrawal** [comment]
I'll set the ci to run on ubuntu 18 for now, we can change we figure this out.

**Comment by lloydbond** [comment]
I have the same issue with Ubuntu 21.04 aarch64 when running Hyper-3.1.2-arm64.AppImage

`> ./Hyper-3.1.2-arm64.AppImage 
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /tmp/.mount_Hyper-qN9aGx/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /tmp/.mount_Hyper-qN9aGx/resources/app.asar/node_modules/node-pty/lib/index.js
- /tmp/.mount_Hyper-qN9aGx/resources/app.asar/session.js
- /tmp/.mount_Hyper-qN9aGx/resources/app.asar/ui/window.js
- /tmp/.mount_Hyper-qN9aGx/resources/app.asar/index.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function._load (/tmp/.mount_Hyper-qN9aGx/resources/app.asar/plugins.js:99:37)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/tmp/.mount_Hyper-qN9aGx/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/.mount_Hyper-qN9aGx/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/tmp/.mount_Hyper-qN9aGx/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/tmp/.mount_Hyper-qN9aGx/resources/app.asar/session.js',
    '/tmp/.mount_Hyper-qN9aGx/resources/app.asar/ui/window.js',
    '/tmp/.mount_Hyper-qN9aGx/resources/app.asar/index.js',
    undefined
  ]
}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: `node-pty` failed to load. Typically this means that it was built incorrectly. Please check the `readme.md` to more info.
    at createNodePtyError (/tmp/.mount_Hyper-qN9aGx/resources/app.asar/session.js:33:34)
    at Object.<anonymous> (/tmp/.mount_Hyper-qN9aGx/resources/app.asar/session.js:40:11)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function._load (/tmp/.mount_Hyper-qN9aGx/resources/app.asar/plugins.js:99:37)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)

`

**Comment by LabhanshAgrawal** [comment]
stale
