### ISSUE TITLE
Hyper can't handle WSL at all on Windows 10

### ISSUE THREAD

**Issue by Sorin-M-Oprea** [vercel/hyper#5889]
- [x] Your Hyper.app version is **3.1.2**. Please verify your using the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate
---
- **Any relevant information from devtools?** _(CMD+OPTION+I on macOS, CTRL+SHIFT+I elsewhere)_:

N/A
- **Is the issue reproducible in vanilla Hyper.app?**

Yes
## Issue

Latest Windows 10. WSL installed and configured with Fedora Remix, or Ubuntu (Doesn't matter). Configure Hyper to run WSL. No matter what I choose for the "Shell:" field in the config, it won't work. Yes, I saved the file. No, I am not getting any error messages, but all the time, Hyper only knows to open CMD and NOTHING else.
My Windows "Users" folder is located on a different partition (not C:), if this helps.

---

- **Hyper version**: undefined "3.1.2"
- **OS ARCH VERSION:** win32 x64 10.0.19043
- **Electron:** 13.1.7  **LANG:** undefined
- **SHELL:** undefined   **TERM:** undefined
<details><summary><strong>.hyper.js contents</strong></summary>

```json
{
  "updateChannel": "stable",
  "fontSize": 12,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "fontWeight": "normal",
  "fontWeightBold": "bold",
  "lineHeight": 1,
  "letterSpacing": 0,
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorAccentColor": "#000",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "selectionColor": "rgba(248,28,229,0.3)",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "workingDirectory": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#C51E14",
    "green": "#1DC121",
    "yellow": "#C7C329",
    "blue": "#0A2FC4",
    "magenta": "#C839C5",
    "cyan": "#20C5C6",
    "white": "#C7C7C7",
    "lightBlack": "#686868",
    "lightRed": "#FD6F6B",
    "lightGreen": "#67F86F",
    "lightYellow": "#FFFA72",
    "lightBlue": "#6A76FB",
    "lightMagenta": "#FD7CFC",
    "lightCyan": "#68FDFE",
    "lightWhite": "#FFFFFF",
    "limeGreen": "#32CD32",
    "lightCoral": "#F08080"
  },
  "shell": "C:\\Windows\\System32\\wsl.exe",
  "shellArgs": [
    "--login"
  ],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false,
  "defaultSSHApp": true,
  "quickEdit": false,
  "macOptionSelectionMode": "vertical",
  "webGLRenderer": true,
  "webLinksActivationKey": "",
  "disableLigatures": false,
  "disableAutoUpdates": false
}
```
</details>
<details><summary><strong>plugins</strong></summary>

```json
{
  "plugins": [],
  "localPlugins": []
}
```
</details>

**Comment by LabhanshAgrawal** [comment]
run `hyper -v` from cmd and post the output

**Comment by Sorin-M-Oprea** [comment]
I ran it and got this:

```
Z:\Users\sorin>hyper -v


Disabling Chromium GPU blacklist

running in prod mode
electron will open file://Z:\Users\sorin\AppData\Local\Programs\Hyper\resources\app.asar\index.html

[4868:0825/093339.552:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[4868:0825/093339.552:ERROR:cache_util.cc(144)] Unable to move cache folder Z:\Users\sorin\AppData\Roaming\Hyper\GPUCache to Z:\Users\sorin\AppData\Roaming\Hyper\old_GPUCache_000

[4868:0825/093339.552:ERROR:disk_cache.cc(184)] Unable to create cache
[4868:0825/093339.552:ERROR:shader_disk_cache.cc(606)] Shader Cache Creation failed: -2

[4868:0825/093339.568:WARNING:accelerator_util.cc(63)]  doesn't contain a valid key
[4868:0825/093339.568:WARNING:accelerator_util.cc(63)]  doesn't contain a valid key

[4868:0825/093339.568:WARNING:keyboard_util.cc(135)] Invalid accelerator token: del
[4868:0825/093339.568:WARNING:accelerator_util.cc(63)] ctrl+del doesn't contain a valid key

Hyper CLI already in PATH

Hyper CLI installed You may need to restart your computer to complete this installation process. undefined

[4868:0825/093339.780:INFO:CONSOLE(13)] "(electron) The remote module is deprecated. Use https://github.com/electron/remote instead.", source: electron/js2c/renderer_init.js (13)

[4868:0825/093339.787:INFO:CONSOLE(1)] "(re)loading renderer plugins", source: file:///Z:/Users/sorin/AppData/Local/Programs/Hyper/resources/app.asar/renderer/bundle.js (1)

[4868:0825/093339.885:INFO:CONSOLE(36)] "total init time 147.40000000596046", source: file:///Z:/Users/sorin/AppData/Local/Programs/Hyper/resources/app.asar/index.html (36)

Checking for notification messages

Error: Cannot resize a pty that has already exited
    at WindowsPtyAgent.resize (Z:\Users\sorin\AppData\Local\Programs\Hyper\resources\app.asar\node_modules\node-pty\lib\windowsPtyAgent.js:137:23)     
    at WindowsTerminal.<anonymous> (Z:\Users\sorin\AppData\Local\Programs\Hyper\resources\app.asar\node_modules\node-pty\lib\windowsTerminal.js:131:26)
    at WindowsTerminal._defer (Z:\Users\sorin\AppData\Local\Programs\Hyper\resources\app.asar\node_modules\node-pty\lib\windowsTerminal.js:156:24)     
    at WindowsTerminal.resize (Z:\Users\sorin\AppData\Local\Programs\Hyper\resources\app.asar\node_modules\node-pty\lib\windowsTerminal.js:130:14)     
    at Session.resize (Z:\Users\sorin\AppData\Local\Programs\Hyper\resources\app.asar\session.js:191:26)
    at Server.<anonymous> (Z:\Users\sorin\AppData\Local\Programs\Hyper\resources\app.asar\ui\window.js:168:21)
    at Server.emit (events.js:315:20)
    at Server.ipcListener (Z:\Users\sorin\AppData\Local\Programs\Hyper\resources\app.asar\rpc.js:31:15)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9469)


shell exited in 206 ms with exit code 4294967295
please check the shell config: {
  "shell": "C:\\Windows\\System32\\wsl.exe",    
  "shellArgs": [
    "-i"
  ]
}
fallback to default shell config: {
  "shell": "C:\\WINDOWS\\system32\\cmd.exe",    
  "shellArgs": [
    "--login"
  ]
}


No matching notification messages

Error fetching updates Can not find Squirrel (Error: Can not find Squirrel
    at AutoUpdater.checkForUpdates (electron/js2c/browser_init.js:17:1405)
    at checkForUpdates (Z:\Users\sorin\AppData\Local\Programs\Hyper\resources\app.asar\updater.js:49:21))
```

**Comment by LabhanshAgrawal** [comment]
```
shell exited in 206 ms with exit code 4294967295
please check the shell config: {
  "shell": "C:\\Windows\\System32\\wsl.exe",    
  "shellArgs": [
    "-i"
  ]
}
fallback to default shell config: {
  "shell": "C:\\WINDOWS\\system32\\cmd.exe",    
  "shellArgs": [
    "--login"
  ]
}
```
It's falling back to CMD as wsl exited in 206ms
You can try and remove the "-i" shellArg
You'd have exe's for ubuntu or fedora directly also, right?
You can set that and try.
You can test whatever config you use, by running `<shell> <shellArgs>` in CMD first and seeing if it's opening your shell.

**Comment by LabhanshAgrawal** [comment]
See https://github.com/microsoft/WSL/issues/5092 also

**Comment by Sorin-M-Oprea** [comment]
Using directly the exe gives me this:

```
Z:\Users\sorin>"C:\Program Files\WindowsApps\WhitewaterFoundryLtd.Co.FedoraRemixforWSL_34.5.6.0_x64__kd1vv0z0vy70w\fedoraremix.exe"
Access is denied.
```

Starting WSL with no argument does nothing:

```
Z:\Users\sorin>C:\\Windows\\System32\\wsl.exe

Z:\Users\sorin>
```

Starting WSL manually with the distro argument will actually drop into WSL (works from any drive not just C:):

```
Z:\Users\sorin>c:

C:\>C:\\Windows\\System32\\wsl.exe -d fedoraremix
sorin in /mnt/c λ
```

Good, right? But then I change the config with this:

```
shell: 'C:\\Windows\\System32\\wsl.exe',
shellArgs: ['-d fedoraremix'],
```

Then I start a new window, and I still get CMD. Running the `hyper -v` command and I get this now:

```
Z:\Users\sorin>hyper -v


Disabling Chromium GPU blacklist

running in prod mode
electron will open file://Z:\Users\sorin\AppData\Local\Programs\Hyper\resources\app.asar\index.html

[4852:0825/100254.959:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[4852:0825/100254.959:ERROR:cache_util.cc(144)] Unable to move cache folder Z:\Users\sorin\AppData\Roaming\Hyper\GPUCache to Z:\Users\sorin\AppData\Roaming\Hyper\old_GPUCache_000

[4852:0825/100254.959:ERROR:disk_cache.cc(184)] Unable to create cache
[4852:0825/100254.959:ERROR:shader_disk_cache.cc(606)] Shader Cache Creation failed: -2

[4852:0825/100254.973:WARNING:accelerator_util.cc(63)]  doesn't contain a valid key
[4852:0825/100254.973:WARNING:accelerator_util.cc(63)]  doesn't contain a valid key

[4852:0825/100254.973:WARNING:keyboard_util.cc(135)] Invalid accelerator token: del
[4852:0825/100254.973:WARNING:accelerator_util.cc(63)] ctrl+del doesn't contain a valid key

Hyper CLI already in PATH

Hyper CLI installed You may need to restart your computer to complete this installation process. undefined

[4852:0825/100255.169:INFO:CONSOLE(13)] "(electron) The remote module is deprecated. Use https://github.com/electron/remote instead.", source: electron/js2c/renderer_init.js (13)

[4852:0825/100255.176:INFO:CONSOLE(1)] "(re)loading renderer plugins", source: file:///Z:/Users/sorin/AppData/Local/Programs/Hyper/resources/app.asar/renderer/bundle.js (1)

[4852:0825/100255.273:INFO:CONSOLE(36)] "total init time 144", source: file:///Z:/Users/sorin/AppData/Local/Programs/Hyper/resources/app.asar/index.html (36)

Checking for notification messages


shell exited in 279 ms with exit code 1
please check the shell config: {
  "shell": "C:\\Windows\\System32\\wsl.exe",
  "shellArgs": [
    "[",
    "'",
    "-",
    "d",
    " ",
    "f",
    "e",
    "d",
    "o",
    "r",
    "a",
    "r",
    "e",
    "m",
    "i",
    "x",
    "'",
    "]"
  ]
}
fallback to default shell config: {
  "shell": "C:\\WINDOWS\\system32\\cmd.exe",
  "shellArgs": [
    "--login"
  ]
}


No matching notification messages

Error fetching updates Can not find Squirrel (Error: Can not find Squirrel
    at AutoUpdater.checkForUpdates (electron/js2c/browser_init.js:17:1405)
    at checkForUpdates (Z:\Users\sorin\AppData\Local\Programs\Hyper\resources\app.asar\updater.js:49:21))
```

I even tried setting the args to these variants but got literally the same error (formatted on multiple lines like above):

```
shellArgs: "['-d fedoraremix']",
shellArgs: \`['-d fedoraremix']\`,
shellArgs: \`["-d fedoraremix"]\`,
```

Setting the args to `shellArgs: ["-d fedoraremix"],` will still throw the error but at least it will show the args on the same line in the error message:

```
shell exited in 128 ms with exit code 1
please check the shell config: {
  "shell": "C:\\Windows\\System32\\wsl.exe",
  "shellArgs": [
    "-d fedoraremix"
  ]
}
fallback to default shell config: {
  "shell": "C:\\WINDOWS\\system32\\cmd.exe",
  "shellArgs": [
    "--login"
  ]
}
```

**Comment by LabhanshAgrawal** [comment]
Use `shellArgs: ["-d", "fedoraremix"]`

**Comment by Sorin-M-Oprea** [comment]
> 
> 
> Use `shellArgs: ["-d", "fedoraremix"]`

This actually worked. Thanks.

**Comment by LabhanshAgrawal** [comment]
You're welcome.
To be able to use wsl.exe directly, I think you need to set the default distro.
