### ISSUE TITLE
Hyper open in blank, even if i type something im not able to see anything in the screen

### ISSUE THREAD

**Issue by CsarGomez** [vercel/hyper#6062]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.15.7 - Catalina
- **Hyper.app version**: 3.1.4(stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/CsarGomez/04c86e14484ab0d29985636609ac49ac
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

### Description:
Hyper.js open in blank, and without text. even if i type something it doesn't display any word typed.
previous issues related suggest to to disable hyperborder plugin, but i realize that i don't have that plugin on my list.
It was working good until yesterday, can someone came with some tips or things that ti can try?
### things i already try:
- add hyperborder to the plugins and disable (doesn't work for me)
- add hyper2-border to the plugins and disable (works for a moment, but after restart or close and reopen the terminal the issue still there)

**Comment by CsarGomez** [comment]
![Captura de Pantalla 2021-10-30 a la(s) 7 01 26 a  m](https://user-images.githubusercontent.com/5133753/139532589-ee8f7751-65e4-4edc-978a-afd875106ded.png)

**Comment by megavolt666eblan** [comment]
Im sorry, its not my issue, you mistake with the recipient of this messege

сб, 30 окт. 2021 г., 15:18 Cesar Gomez ***@***.***>:

**Comment by taigadigital** [comment]
Confirming this issue on MacOS Monterey

**Comment by LabhanshAgrawal** [comment]
@CsarGomez try with the default config once
You can just delete the current one using `rm ~/.hyper.js` and hyper will generate the config file again.

**Comment by CsarGomez** [comment]
@LabhanshAgrawal @taigadigital 
thanks for the feedback, i did what you suggest but doesn't work for me.
what works for me is turn WebGL rendering to False.
hope that can help to others with same issue

**Comment by nickand-code** [comment]
@LabhanshAgrawal  Thanks for a suggestion! Worked for Windows 10.

**Comment by andrewclo** [comment]
I am experiencing this issue also with MacOS Monterey. 12.0.1

**Comment by CsarGomez** [comment]
@andrewclo i was able to fix it by turn WebGL rendering to False.

**Comment by LabhanshAgrawal** [comment]
@CsarGomez can you please try again with webgl set to true and report the output of `hyper -v` and the output from dev console (cmd+opt+i)
This will help in identifying the root issue

**Comment by CsarGomez** [comment]
@LabhanshAgrawal  i set webgl to true but doesn't work, i get the same issue as i report
hyper -v doesn't do anything, it just return: zsh: command not found: hyper

**Comment by LabhanshAgrawal** [comment]
What's the output on Dev console (cmd+option +i)
You can add the hyper command using 'tools' >'install hyper command to pay' menu item.

**Comment by CsarGomez** [comment]
@LabhanshAgrawal here's the result:

 ✝  ~  hyper -v
Plugin hyperterm-cobalt2-theme (2.0.0) loaded.

[Function (anonymous)] {
  [Symbol(nodejs.util.promisify.custom)]: [Function (anonymous)]
}
Plugin fig-hyper-integration (undefined) loaded.

No package.json found in /Users/cesargomez/.hyper_plugins/local/fig-hyper-integration

Disabling Chromium GPU blacklist

running in prod mode
electron will open file:///Applications/Hyper.app/Contents/Resources/app.asar/index.html

Hyper CLI already in PATH
Hyper CLI installed Symlink created at /usr/local/bin/hyper undefined

[7041:1125/141033.540684:INFO:CONSOLE(13)] "(electron) The remote module is deprecated. Use https://github.com/electron/remote instead.", source: electron/js2c/renderer_init.js (13)

[7041:1125/141033.558006:INFO:CONSOLE(1)] "(re)loading renderer plugins", source: file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js (1)

[7041:1125/141033.588375:INFO:CONSOLE(1)] "Plugin hyperterm-cobalt2-theme (2.0.0) loaded.", source: file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js (1)

[7041:1125/141033.590246:INFO:CONSOLE(1)] "No package.json found in /Users/cesargomez/.hyper_plugins/local/fig-hyper-integration", source: file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js (1)

[7041:1125/141033.591952:INFO:CONSOLE(2)] "function i(e,t,r){"function"==typeof t&&(r=t,t={}),n.ipcRenderer.invoke("child_process.exec",{command:e,options:t}).then(({stdout:e,stderr:t})=>{var n;return null===(n=r)||void 0===n?void 0:n(null,e,t)},e=>{var t;return null===(t=r)||void 0===t?void 0:t(e,"","")})}", source: /Applications/Fig.app/Contents/Resources/hyper-integration.js (2)

[7041:1125/141033.592046:INFO:CONSOLE(1)] "Plugin fig-hyper-integration (null) loaded.", source: file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js (1)

[7041:1125/141033.840610:INFO:CONSOLE(36)] "total init time 381.8999999985099", source: file:///Applications/Hyper.app/Contents/Resources/app.asar/index.html (36)

Checking for notification messages

sysctl: unknown oid 'sysctl.proc_translated'

Failed to detect Rosetta

[7041:1125/141034.297677:INFO:CONSOLE(7)] "SESSION_ADD 9ce8158d-1268-4d89-9210-da0808e34c57", source: /Applications/Fig.app/Contents/Resources/hyper-integration.js (7)

Error occurred in handler for 'child_process.exec': Error: Command failed: ~/.fig/bin/fig keyboard-focus-changed hyper 9ce8158d
Error: unknown command "keyboard-focus-changed" for "fig"
Run 'fig --help' for usage.

    at ChildProcess.exithandler (child_process.js:317:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '~/.fig/bin/fig keyboard-focus-changed hyper 9ce8158d',
  stdout: '',
  stderr: 'Error: unknown command "keyboard-focus-changed" for "fig"\n' +
    "Run 'fig --help' for usage.\n"
}

No matching notification messages

**Comment by LabhanshAgrawal** [comment]
The error messages are from `fig-hyper-integration` local extension. Can you try once after removing that? You can move it to some other directory to test and then copy back.

**Comment by gscottolson** [comment]
Same for me. macOS Monterey 12.0.1. Error in the console is…

`bundle.js:1 Uncaught Error: No valid cmap sub-tables found.`

**Comment by CsarGomez** [comment]
@LabhanshAgrawal sorry for the delay.
no, i got the issue 3 weeks before i installed fig
