### ISSUE TITLE
Fast open/close bug (sometimes while GIT process is executed)

### ISSUE THREAD

**Issue by dweidenfeld** [vercel/hyper#609]
Hey there,

I'm running hyperterm in OS X El Capitan and facing an issue.
The issue sometimes occur if I execute some git commands (mostly pull/push). But it is often reproducable if you fast open a new terminal and instantly close the window with CMD + w.

The error looks like this:

```
A JavaScript error occurred in the main process
```

``` javascript
Uncaught Exception:
Error: Object has been destroyed
    at Error (native)
    at Server.get wc [as wc] (/Applications/HyperTerm.app/Contents/Resources/app/rpc.js:28:20)
    at Server.emit (/Applications/HyperTerm.app/Contents/Resources/app/rpc.js:36:9)
    at Session.session.on (/Applications/HyperTerm.app/Contents/Resources/app/index.js:100:15)
    at emitOne (events.js:96:13)
    at Session.emit (events.js:188:7)
    at PtyRwStream.Session.pty.stdout.on (/Applications/HyperTerm.app/Contents/Resources/app/session.js:41:12)
    at emitOne (events.js:96:13)
    at PtyRwStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
```

There is no direct error that would affect my actions, but it is a bit annoying if the error dialog pops up even if there is no actual error happening for the end user.

Could you please check if you can add a try-catch block around this error to quite it?

Thanks ;)

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Comment by shawwn** [comment]
@Stanzilla I'm getting this on Windows 10 with the latest hyper v2.

![image](https://user-images.githubusercontent.com/59632/39409714-9c03068c-4bb1-11e8-9717-37b070b8ebb9.png)

You may want to reopen this issue.
