### ISSUE TITLE
error on installing theme pluging 

### ISSUE THREAD

**Issue by Faniry2** [vercel/hyper#6138]
when i try to install theme a got this issue 
Error fetching updates Can not find Squirrel (Error: Can not find Squirrel
    at AutoUpdater.checkForUpdates (electron/js2c/browser_init.js:17:1405)
    at checkForUpdates (C:\Users\USER\AppData\Local\Programs\Hyper\resources\app.asar\updater.js:49:21))

**Comment by LabhanshAgrawal** [comment]
Please fill the issue template
Also what command are you running to install the plugin
