### ISSUE TITLE
[M1 MAC]　I get a javascript error when installing

### ISSUE THREAD

**Issue by YunosukeYoshino** [vercel/hyper#6463]
# I get a javascript error when installing

My environment
- m1 mac Monterey 12.3
- hyper ver3.2.2

Error message
```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: Error reading configuration: `module.exports` not set
at _extract (/Applications/Hyper.app/Contents/Resources/app.asar/config/init.js:14:15)
at _init (/Applications/Hyper.app/Contents/Resources/app.asar/config/init.js:35:28)
at _import (/Applications/Hyper.app/Contents/Resources/app.asar/config/import.js:113:37)
at Object.setup (/Applications/Hyper.app/Contents/Resources/app.asar/config.js:99:32)
at Object.<anonymous> (/Applications/Hyper.app/Contents/Resources/app.asar/index.js:50:8)
at Module._compile (node:internal/modules/cjs/loader:1116:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
at Module.load (node:internal/modules/cjs/loader:988:32)
at Module._load (node:internal/modules/cjs/loader:829:12)
at Function.c._load (node:electron/js2c/asar_bundle:5:13331)

```

**Comment by LabhanshAgrawal** [comment]
your config is malformed
check and  update or delete it

**Comment by carlosbensant** [comment]
[YunosukeYoshino](https://github.com/YunosukeYoshino) Try deleting that copy of the installer and re-downloading a fresh one.

I just downloaded a new copy of Hyper from https://hyper.is and it's running as expected. reference: https://prnt.sc/uX23Tqy-XO9F
- M1 MacOS Monterey 12.2.1
- Hyper 3.2.2

Let us know if you're having the same issue.

**Comment by brandontan** [comment]
I have the same error as @YunosukeYoshino .. it's a brand new mac book pro : 12.3.1

**Comment by LabhanshAgrawal** [comment]
> I have the same error as @YunosukeYoshino .. it's a brand new mac book pro : 12.3.1

can you post your config file contents `~/.hyper.js`

**Comment by YunosukeYoshino** [comment]
@carlosbensant The error has occurred again....

**Comment by LabhanshAgrawal** [comment]
@YunosukeYoshino post your config

**Comment by YunosukeYoshino** [comment]
↓The file was not found.
~/Library/Application Support/Hyper/.hyper.js

**Comment by LabhanshAgrawal** [comment]
> > I have the same error as @YunosukeYoshino .. it's a brand new mac book pro : 12.3.1
> 
> can you post your config file contents `~/.hyper.js`

@YunosukeYoshino it'd be in the home directory

**Comment by brandontan** [comment]
This is my .hyper.js
<img width="1722" alt="CleanShot 2022-04-17 at 11 17 17@2x" src="https://user-images.githubusercontent.com/1005474/163698730-fd16417c-4e50-4a7c-9ebf-855465fd592b.png">

**Comment by YunosukeYoshino** [comment]
@brandontan 
@LabhanshAgrawal  
I was in the same place
