### ISSUE TITLE
Cannot find module '../build/Debug/pty.node' in Debian arm64 build

### ISSUE THREAD

**Issue by toaster42** [vercel/hyper#6502]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Chrome OS Version 100.0.4896.133 (Official Build) (32-bit) running Debian GNU/Linux 11 (bullseye) in crostini

- **Hyper.app version**: 3.2.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: ~/.config/Hyper/.hyper.js does not exist 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

Hyper.app will not open. running `hyper -v` yields the following output:
```
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Hyper/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /opt/Hyper/resources/app.asar/node_modules/node-pty/lib/index.js
- /opt/Hyper/resources/app.asar/session.js
- /opt/Hyper/resources/app.asar/ui/window.js
- /opt/Hyper/resources/app.asar/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Function._load (/opt/Hyper/resources/app.asar/plugins.js:103:37)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/opt/Hyper/resources/app.asar/session.js',
    '/opt/Hyper/resources/app.asar/ui/window.js',
    '/opt/Hyper/resources/app.asar/index.js',
    undefined
  ]
}

A JavaScript error occurred in the main process
Uncaught Exception:
Error: `node-pty` failed to load. Typically this means that it was built incorrectly. Please check the `readme.md` to more info.
    at createNodePtyError (/opt/Hyper/resources/app.asar/session.js:39:34)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/session.js:46:11)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Function._load (/opt/Hyper/resources/app.asar/plugins.js:103:37)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)

[3011:0426/102842.244860:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.

[3050:0426/102842.519017:ERROR:angle_platform_impl.cc(44)] renderergl_utils.cpp:188 (ClearErrors): Preexisting GL error 0x00000500 as of ../../third_party/angle/src/libANGLE/renderer/gl/TextureGL.cpp, setImageHelper:256. 
```

not sure if it's relevant (mainly just for the architecture), but here's the output of `lscpu` as well:
```
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              1
Core(s) per socket:              8
Socket(s):                       1
Vendor ID:                       Qualcomm
Model:                           14
Stepping:                        0xd
BogoMIPS:                        38.40
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcp
                                 c dcpop asimddp
```

I see that Node CI is failing, the linux arm64 build failing in this manner might be related.

**Comment by Rudya93** [comment]
Hello, got the same issue

innerError Error: Cannot find module '../build/Debug/pty.node'

`innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/OpenLens/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /opt/OpenLens/resources/app.asar/node_modules/node-pty/lib/index.js
- /opt/OpenLens/resources/app.asar/static/build/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/OpenLens/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/OpenLens/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/OpenLens/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/opt/OpenLens/resources/app.asar/static/build/main.js',
    undefined
  ]
}
(node:1624) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `open-lens --trace-deprecation ...` to show where the warning was created)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.9sDm3X: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Module._extensions..node (node:internal/modules/cjs/loader:1203:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/OpenLens/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
[1689:1114/092555.207761:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.216935:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.218071:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.218944:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.219662:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.220357:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.221070:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.223567:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.224873:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.226930:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.228213:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.229024:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.230288:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.230801:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.232001:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.232291:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.232598:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.232859:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.233138:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.233401:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.233623:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.233882:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.234112:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.234377:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.234606:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.234845:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.235043:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.235373:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.235680:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.235953:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.236830:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.237887:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.238234:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.238563:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.250172:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.251620:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.253569:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.255909:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.259720:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[1689:1114/092555.262218:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
lin@penguin:~/Code/sobol/jdblayer-terraform-prod-01/layers/revive$ lscpu
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              1
Core(s) per socket:              8
Socket(s):                       1
Vendor ID:                       Qualcomm
Model:                           14
Stepping:                        0xd
BogoMIPS:                        38.40
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop 
                                 asimddp`

**Comment by Rudya93** [comment]
@toaster42 , did you able to fix it?

**Comment by LabhanshAgrawal** [comment]
We'd made some progress with better arm64 builds, I'd put it on hold as I got caught up with things, but I'm back on track now, so this is back on todo.

**Comment by toaster42** [comment]
> @toaster42 , did you able to fix it?

@Rudya93 No, I have not.  Thankfully the devs are on the case!

**Comment by LabhanshAgrawal** [comment]
I've got an arm64 device, will start working on this

**Comment by LabhanshAgrawal** [comment]
I've opened https://github.com/vercel/hyper/pull/7227 for this
Please try the build from that PR and check if it works for you. (you can find it from the checks section or from the latest comment by github actions bot.)
