### ISSUE TITLE
Ubuntu 22.04 cannot start the latest version of hyper!

### ISSUE THREAD

**Issue by xmhwws** [vercel/hyper#6783]
- [ yes] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [ yes] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: <Ubuntu 22.04 LTS>
- **Hyper.app version**: <3.3.0_amd64>
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
After running hyper only the content inside the figure, no .hyper.js
![d3a6dc1a9b1e46c53670a36d82aff54](https://user-images.githubusercontent.com/42903751/192206979-47e12660-c96e-418e-878b-f7e946585aee.jpg)

- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

```
sudo dpkg -i hyper_3.3.0_amd64.deb
hyper
```
No hyper's interface is displayed, which means the startup failed.

`hyper -v`
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Error reading configuration: `module.exports` not set
    at _extract (/opt/Hyper/resources/app.asar/config/init.js:14:15)
    at _init (/opt/Hyper/resources/app.asar/config/init.js:35:28)
    at _import (/opt/Hyper/resources/app.asar/config/import.js:113:37)
    at Object.setup (/opt/Hyper/resources/app.asar/config.js:99:32)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/index.js:50:8)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
[5991:0926/141605.819635:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
[6023:0926/141605.910177:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: 没有那个文件或目录 (2)
```

**Comment by LabhanshAgrawal** [comment]
The config file would be in the home directory. You may delete it to reset it.

**Comment by armanzor** [comment]
You may use AppImage, it works well on 22.04

**Comment by Aleksej579** [comment]
I had the same error, Hyper terminal was running but not displayed. Solution - deleted the .hyper.js file and everything worked.
