### ISSUE TITLE
The latest version 4.0-canary3 reported an error for the mac m2-VM kali arm64

### ISSUE THREAD

**Issue by soibhanZhangxb** [vercel/hyper#7071]
──(soibhan㉿kali)-[~]
└─$ hyper -v
Plugin hyperinator (0.4.4) loaded.

Plugin hyperpwn (0.4.2) loaded.

innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Hyper/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /opt/Hyper/resources/app.asar/node_modules/node-pty/lib/index.js
- /opt/Hyper/resources/app.asar/session.js
- /opt/Hyper/resources/app.asar/ui/window.js
- /opt/Hyper/resources/app.asar/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13339)
    at Function._load (/opt/Hyper/resources/app.asar/plugins.js:103:37)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:34:15)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/opt/Hyper/resources/app.asar/session.js',
    '/opt/Hyper/resources/app.asar/ui/window.js',
    '/opt/Hyper/resources/app.asar/index.js',
    undefined
  ]
}

A JavaScript error occurred in the main process
Uncaught Exception:                                                                                                                  
Error: `node-pty` failed to load. Typically this means that it was built incorrectly. Please check the `readme.md` to more info.     
    at createNodePtyError (/opt/Hyper/resources/app.asar/session.js:39:34)                                                           
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/session.js:46:11)                                                           
    at Module._compile (node:internal/modules/cjs/loader:1120:14)                                                                    
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)                                                             
    at Module.load (node:internal/modules/cjs/loader:988:32)                                                                         
    at Module._load (node:internal/modules/cjs/loader:829:12)                                                                        
    at c._load (node:electron/js2c/asar_bundle:5:13339)                                                                              
    at Function._load (/opt/Hyper/resources/app.asar/plugins.js:103:37)                                                              
    at Module.require (node:internal/modules/cjs/loader:1012:19)                                                                     
    at require (node:internal/modules/cjs/helpers:102:18)                                                                            

(hyper:2166): Gtk-WARNING **: 06:56:23.474: Theme parsing error: gtk.css:2827:15: Not using units is deprecated. Assuming 'px'.

[2166:0320/065623.532322:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.

libGL error: pci id for fd 19: 1ab8:0010, driver (null)

pci id for fd 20: 1ab8:0010, driver (null)

[2201:0320/065623.604139:WARNING:sandbox_linux.cc(380)] InitializeSandbox() called with multiple threads in process gpu-process.

pci id for fd 38: 1ab8:0010, driver (null)

pci id for fd 39: 1ab8:0010, driver (null)

[2201:0320/065623.612470:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.612939:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.613148:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.613427:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.613588:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.613746:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.614007:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.614168:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.614314:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.614463:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.614594:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.614719:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.614843:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.614971:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.615191:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.615322:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.615559:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.615693:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.615821:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.615952:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.616074:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.616201:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.616317:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.616436:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.616563:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.626275:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.626548:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.626648:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.626900:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.627045:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.627182:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.627310:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.627441:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.627561:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.627697:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.627821:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.627955:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.628075:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.628198:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

[2201:0320/065623.628325:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: No such file or directory (2)

**Comment by soibhanZhangxb** [comment]
Jai-JAP successed build hyper for linux arm64, very great!

https://github.com/Jai-JAP/hyper-arm-builds

**Comment by LabhanshAgrawal** [comment]
thanks for linking, will take a look

**Comment by LabhanshAgrawal** [comment]
I've opened https://github.com/vercel/hyper/pull/7227 for this
Please try the build from that PR and check if it works for you. (you can find it from the checks section or from the latest comment by github actions bot.)
