### ISSUE TITLE
Tab crashes when opening in a missing CWD

### ISSUE THREAD

**Issue by Artemis21** [vercel/hyper#7581]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Fedora 38
- **Hyper.app version**: 3.4.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your hyper.json**: [hyper config gist](https://gist.github.com/Artemis21/a3b0161175020f547d39520271afc66a)
- **Relevant information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**: No change after disabling all extensions. Presumably config with `preserveCWD: true` would not be affected by the same steps.

## Issue

Steps:
1. Launch hyper
2. Have `preserveCWD: true` in config
3. `mkdir test`
4. `cd test`
5. `rm -r ../test`
6. Open a new tab

Observed:
Error messages scrolling by very quickly, followed by the tab closing.

Expected:
A new tab to open in the closest existing ancestor of the missing directory, or other reasonable fall-back behaviour.

Notes:
- This happens with both fish and sh shells.
- A screenshot showing part of the error message seen. Most or all of the errors appear to be the same as this, though it goes too fast for me to be sure (also, it closes too fast for me to copy the text, so please excuse the screenshot). ![the image just described](https://github.com/vercel/hyper/assets/57376638/03abcd43-710d-48b7-8bd6-66271775f8d7)
- Running the `hyper` command from a missing directory also fails:
  ```
  shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
  node:internal/bootstrap/switches/does_own_process_state:126
      cachedCwd = rawMethods.cwd();
                           ^

  Error: ENOENT: no such file or directory, uv_cwd
      at process.wrappedCwd [as cwd] (node:internal/bootstrap/switches/does_own_process_state:126:28)
      at t.find (/opt/Hyper/resources/bin/cli.js:2:152432)
      at e.exports (/opt/Hyper/resources/bin/cli.js:2:151343)
      at i (/opt/Hyper/resources/bin/cli.js:2:150626)
      at Module.<anonymous> (/opt/Hyper/resources/bin/cli.js:2:148380)
      at r (/opt/Hyper/resources/bin/cli.js:2:614310)
      at /opt/Hyper/resources/bin/cli.js:2:614977
      at /opt/Hyper/resources/bin/cli.js:2:618469
      at Object.<anonymous> (/opt/Hyper/resources/bin/cli.js:2:618473)
      at Module._compile (node:internal/modules/cjs/loader:1120:14) {
    errno: -2,
    code: 'ENOENT',
    syscall: 'uv_cwd'
  }
  ```
- The same issue is not observed in gnome terminal.

**Comment by Artemis21** [comment]
A check for this case seems to have been added [in this commit](https://github.com/vercel/hyper/commit/bafa44845a9d0963025fe0c4223fbc2114e56966#diff-ead9a731737a91338f5c582986f49f7c41e8ceff4e6fa0542e2ca7c9960e3840R142), not sure why that's not working
